### ISSUE TITLE
CTD when starting up minecraft

### ISSUE THREAD

**Issue by DatrixTHLK** [TeamMion/MoreFood#1]
Crash Log: https://gist.github.com/DatrixTHLK/4b948f2fb566d25d8e083f2aa67e7c4f
Minecraft 1.10.2
Forge: 12.18.2.2116
Mioncore: 1.0.0
tm-morefoods: 1.0.0

**Comment by stefanwimmer128** [comment]
Issue is fixed in MoreFood 1.0.1

**Comment by DatrixTHLK** [comment]
Thank you. :)
